spring.application.name=ProgInzSeminar1


#konfiguracija ar H2 datubazi
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true

#konfiguracija ar MySQL
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/minirimiPS
spring.datasource.username=userspringPS
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name =com.mysql.jdbc.Driver